### PR TITLE
adding override

### PR DESCRIPTION
**Pull request by Lite5h4dow**
allow the style to be overridden

### CODE REVIEW

**Comment by Sharcoux** [comment]
Hey, thanks for the PR

Sorry for the delay, We were in holidays

Can you give me an example of why you would want to override the style of the wrapper? Can't this be achieved by updating the style of the container?

**Comment by Lite5h4dow** [comment]
No, because whatever you do there is always a border, i didnt want a gap between the inner slider and the background. This causes issues matching the radius of the inner and outer elements and can leave an ugly missmatch.

**Comment by Sharcoux** [comment]
Sorry, can you illustrate with a screenshot? It's not clear to me what you mean exactly.

**Comment by Sharcoux** [comment]
This should have been solved in earlier releases. I'll close.

**Pull request closed without merging**
